apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service-nex
          image: quixxy/nexmedis:v1
          env:
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_PORT
              value: "3308"
      imagePullSecrets:
        - name: be-secret
