apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 7899
      targetPort: 7899
      nodePort: 30099
  selector:
    app: backend-service