name: Build

on:
  push:
    branches:
      - master
    paths:
      - "ecommerce-api/**"
  pull_request:
    branches:
      - master
    paths:
      - "ecommerce-api/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify directory exists
        run: ls -l

      - name: Set Commit Hash as Tag
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        working-directory: ecommerce-api
        run: |
          IMAGE_NAME=nexmedis
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ env.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ env.TAG }}